### ISSUE TITLE
Docker volumes as host path

### ISSUE THREAD

**Issue by justinvoelker** [mayan-edms/mayan-edms#271]
Consider the following docker-compose.yml:

```
version: '3'
services:
  mayan:
    image: mayanedms/mayanedms:2.7.3
    container_name: edms-test
    volumes:
      - ./mayan_data:/var/lib/mayan
```

When the above docker-compose is started, the container exits with the following errors:

```
edms-test | mayan.settings <7> [ERROR] "<module>() Error importing user's local.py; No module named media.settings.local"
edms-test | cp: cannot create regular file '/usr/local/lib/python2.7/dist-packages/mayan/media/settings/local.py': No such file or directory
```

When searching for a resolution all I can find is that I "need to used named volumes" which to me is an unacceptable answer. I keep all of my docker container data in the same directory as the docker-compose.yml which allows me to backup or move the container by moving one single directory. Having the data managed by Docker in a completely separate directory eliminates this possibility.

What exactly is missing from the Docker image that does not copy/create the appropriate files if they do not exist? It would seem that all that should be needed is to identify a missing file (such as when an empty directory is mounted as a volume) and copy in the appropriate file(s). I do this exact thing in my own Docker images and it works beautifully.
